version: "3"
services:
  api:
    build: .
    environment:
      - PORT=3003
      - INTERVAL=60
    ports:
      - 3003:3003

  mongodb:
    image: mongo:5.0
    ports:
      - 27017:27017
    volumes:
      - ~/apps/mongo:/data/db
    logging:
      driver: none
