// Code generated by MockGen. DO NOT EDIT.
// Source: C:\Users\Vagkl\Documents\go-projects\spamhaus\utils\urlDownload.go

// Package mocks is a generated GoMock package.
package mocks

import (
	domain "assignment/domain"
	reflect "reflect"
	time "time"

	gomock "github.com/golang/mock/gomock"
)

// MockUrlDownloadInterface is a mock of UrlDownloadInterface interface.
type MockUrlDownloadInterface struct {
	ctrl     *gomock.Controller
	recorder *MockUrlDownloadInterfaceMockRecorder
}

// MockUrlDownloadInterfaceMockRecorder is the mock recorder for MockUrlDownloadInterface.
type MockUrlDownloadInterfaceMockRecorder struct {
	mock *MockUrlDownloadInterface
}

// NewMockUrlDownloadInterface creates a new mock instance.
func NewMockUrlDownloadInterface(ctrl *gomock.Controller) *MockUrlDownloadInterface {
	mock := &MockUrlDownloadInterface{ctrl: ctrl}
	mock.recorder = &MockUrlDownloadInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUrlDownloadInterface) EXPECT() *MockUrlDownloadInterfaceMockRecorder {
	return m.recorder
}

// DownloadSingleUrl mocks base method.
func (m *MockUrlDownloadInterface) DownloadSingleUrl(r domain.URLEntry) (*domain.URLEntry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DownloadSingleUrl", r)
	ret0, _ := ret[0].(*domain.URLEntry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DownloadSingleUrl indicates an expected call of DownloadSingleUrl.
func (mr *MockUrlDownloadInterfaceMockRecorder) DownloadSingleUrl(r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DownloadSingleUrl", reflect.TypeOf((*MockUrlDownloadInterface)(nil).DownloadSingleUrl), r)
}

// DownloadUrls mocks base method.
func (m *MockUrlDownloadInterface) DownloadUrls(urls []domain.URLEntry) ([]time.Duration, int, int) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DownloadUrls", urls)
	ret0, _ := ret[0].([]time.Duration)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(int)
	return ret0, ret1, ret2
}

// DownloadUrls indicates an expected call of DownloadUrls.
func (mr *MockUrlDownloadInterfaceMockRecorder) DownloadUrls(urls interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DownloadUrls", reflect.TypeOf((*MockUrlDownloadInterface)(nil).DownloadUrls), urls)
}
